apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: ingest-and-train
spec:
  workspaces:
    - name: shared-workspace
  params:
    - name: deployment-name
      type: string
      description: name of the deployment to be patched
    - name: git-url
      type: string
      description: url of the git repo for the code of deployment
    - name: git-revision
      type: string
      description: revision to be used from repo of the code for deployment
      default: main
    - name: IMAGE
      type: string
      description: image to be build from the code
    - name: ACCESS_KEY
      type: string
      description: minio access_key
    - name: SECRET_KEY
      type: string
      description: minio secret_key
    - name: S3_ENDPOINT
      type: string
      description: minio endpoint    

  tasks:
    - name: fetch-repository
      taskRef:
        name: git-clone
        kind: ClusterTask
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: url
          value: $(params.git-url)
        - name: subdirectory
          value: ""
        - name: deleteExisting
          value: "true"
        - name: revision
          value: $(params.git-revision)
    - name: build
      runAfter:
        - fetch-repository
      taskRef:
        kind: ClusterTask
        name: s2i-python
      workspaces:
        - name: source
          workspace: shared-workspace
      params:
        - name: IMAGE
          value: $(params.IMAGE)
    - name: ingest-train
      taskRef:
        name: ingest-train
      params:
        - name: IMAGE
          value: $(params.IMAGE)
        - name: ACCESS_KEY
          value: $(params.ACCESS_KEY)
        - name: SECRET_KEY
          value: $(params.SECRET_KEY)
        - name: S3_ENDPOINT
          value: $(params.S3_ENDPOINT)
      workspaces:
      - name: source
        workspace: shared-workspace
      runAfter:
      - build