apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    chains.tekton.dev/signed: "true"
  generateName: ingest-and-train-run-
  labels:
    tekton.dev/pipeline: ingest-and-train
  name: ingest-and-train-run-btk95
spec:
  params:
  - name: ACCESS_KEY
    value: minioadmin
  - name: IMAGE
    value: image-registry.openshift-image-registry.svc:5000/$(context.pipelineRun.namespace)/ingest-and-train
  - name: S3_ENDPOINT
    value: http://minio:9000
  - name: SECRET_KEY
    value: minioadmin
  - name: deployment-name
    value: ingest-and-train
  - name: git-url
    value: https://github.com/redhat-na-ssa/stock.git
  pipelineRef:
    name: ingest-and-train
  taskRunTemplate:
    serviceAccountName: pipeline
  timeouts:
    pipeline: 1h0m0s
  workspaces:
  - name: shared-workspace
    emptyDir: {}
    # persistentVolumeClaim:
    #   claimName: my-pipeline-claim-01
