apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-ingest-and-train
spec:
  workspaces:
    - name: shared-workspace
  params:
    - name: git-url
      type: string
      description: url of the git repo for the code
      default: https://github.com/redhat-na-ssa/stock.git
    - name: git-revision
      type: string
      description: revision to be used from repo of the code
      default: gitops
    - name: IMAGE
      type: string
      description: image to be built from the code
      default: image-registry.openshift-image-registry.svc:5000/$(context.pipelineRun.namespace)/ingest-and-train
    - name: S3_ACCESS_KEY_ID
      type: string
      description: minio access_key
      default: minioadmin
    - name: S3_SECRET_ACCESS_KEY
      type: string
      description: minio secret_key
      default: minioadmin
    - name: S3_ENDPOINT
      type: string
      description: minio endpoint
      default: http://minio:9000
  tasks:
    - name: fetch-repository
      taskRef:
        name: git-clone
        kind: ClusterTask
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: url
          value: $(params.git-url)
        - name: subdirectory
          value: ""
        - name: deleteExisting
          value: "true"
        - name: revision
          value: $(params.git-revision)
    - name: build
      runAfter:
        - fetch-repository
      taskRef:
        kind: ClusterTask
        name: s2i-python
      workspaces:
        - name: source
          workspace: shared-workspace
      params:
        - name: IMAGE
          value: $(params.IMAGE)
    - name: ingest-train
      taskRef:
        name: ingest-train
      params:
        - name: IMAGE
          value: $(params.IMAGE)
        - name: S3_ACCESS_KEY_ID
          value: $(params.S3_ACCESS_KEY_ID)
        - name: S3_SECRET_ACCESS_KEY
          value: $(params.S3_SECRET_ACCESS_KEY)
        - name: S3_ENDPOINT
          value: $(params.S3_ENDPOINT)
      workspaces:
      - name: source
        workspace: shared-workspace
      runAfter:
      - build