apiVersion: kubeflow.org/v1
kind: Notebook
metadata:
  annotations:
    notebooks.kubeflow.org/last-activity: "2023-06-21T22:07:57Z"
    notebooks.opendatahub.io/inject-oauth: "true"
    notebooks.opendatahub.io/last-image-selection: tensorflow:2023.1
    notebooks.opendatahub.io/last-size-selection: Demo / Workshop
    notebooks.opendatahub.io/oauth-logout-url: https://rhods-dashboard-redhat-ods-applications.apps.cluster-xx7jv.xx7jv.sandbox1365.opentlc.com/projects/pipelines-tutorial?notebookLogout=stocks
    opendatahub.io/username: opentlc-mgr
    openshift.io/description: ""
    openshift.io/display-name: Stocks
  creationTimestamp: "2023-06-21T20:13:48Z"
  generation: 2
  labels:
    app: stocks
    opendatahub.io/dashboard: "true"
    opendatahub.io/odh-managed: "true"
    opendatahub.io/user: opentlc-2dmgr
  name: stocks
  namespace: pipelines-tutorial
  resourceVersion: "822977"
  uid: 76dc9e56-dccb-4c90-a4ca-c6ce2dcff836
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: nvidia.com/gpu.present
                operator: NotIn
                values:
                - "true"
            weight: 1
      containers:
      - env:
        - name: NOTEBOOK_ARGS
          value: |-
            --ServerApp.port=8888
                              --ServerApp.token=''
                              --ServerApp.password=''
                              --ServerApp.base_url=/notebook/pipelines-tutorial/stocks
                              --ServerApp.quit_button=False
                              --ServerApp.tornado_settings={"user":"opentlc-2dmgr","hub_host":"https://rhods-dashboard-redhat-ods-applications.apps.cluster-xx7jv.xx7jv.sandbox1365.opentlc.com","hub_prefix":"/projects/pipelines-tutorial"}
        - name: JUPYTER_IMAGE
          value: image-registry.openshift-image-registry.svc:5000/redhat-ods-applications/tensorflow:2023.1
        envFrom:
        - secretRef:
            name: minio-connection
        image: image-registry.openshift-image-registry.svc:5000/redhat-ods-applications/tensorflow:2023.1
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /notebook/pipelines-tutorial/stocks/api
            port: notebook-port
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        name: stocks
        ports:
        - containerPort: 8888
          name: notebook-port
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /notebook/pipelines-tutorial/stocks/api
            port: notebook-port
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: "6"
            memory: 20Gi
          requests:
            cpu: "3"
            memory: 10Gi
        volumeMounts:
        - mountPath: /opt/app-root/src
          name: stocks
        workingDir: /opt/app-root/src
      - args:
        - --provider=openshift
        - --https-address=:8443
        - --http-address=
        - --openshift-service-account=stocks
        - --cookie-secret-file=/etc/oauth/config/cookie_secret
        - --cookie-expire=24h0m0s
        - --tls-cert=/etc/tls/private/tls.crt
        - --tls-key=/etc/tls/private/tls.key
        - --upstream=http://localhost:8888
        - --upstream-ca=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        - --email-domain=*
        - --skip-provider-button
        - --openshift-sar={"verb":"get","resource":"notebooks","resourceAPIGroup":"kubeflow.org","resourceName":"stocks","namespace":"$(NAMESPACE)"}
        - --logout-url=https://rhods-dashboard-redhat-ods-applications.apps.cluster-xx7jv.xx7jv.sandbox1365.opentlc.com/projects/pipelines-tutorial?notebookLogout=stocks
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: registry.redhat.io/openshift4/ose-oauth-proxy@sha256:4bef31eb993feb6f1096b51b4876c65a6fb1f4401fee97fa4f4542b6b7c9bc46
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /oauth/healthz
            port: oauth-proxy
            scheme: HTTPS
          initialDelaySeconds: 30
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        name: oauth-proxy
        ports:
        - containerPort: 8443
          name: oauth-proxy
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /oauth/healthz
            port: oauth-proxy
            scheme: HTTPS
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 100m
            memory: 64Mi
          requests:
            cpu: 100m
            memory: 64Mi
        volumeMounts:
        - mountPath: /etc/oauth/config
          name: oauth-config
        - mountPath: /etc/tls/private
          name: tls-certificates
      enableServiceLinks: false
      serviceAccountName: stocks
      volumes:
      - name: stocks
        persistentVolumeClaim:
          claimName: stocks
      - name: oauth-config
        secret:
          defaultMode: 420
          secretName: stocks-oauth-config
      - name: tls-certificates
        secret:
          defaultMode: 420
          secretName: stocks-tls
status:
  conditions:
  - lastProbeTime: "2023-06-21T22:08:25Z"
    lastTransitionTime: "2023-06-21T21:09:19Z"
    status: "True"
    type: Initialized
  - lastProbeTime: "2023-06-21T22:08:25Z"
    lastTransitionTime: "2023-06-21T21:09:40Z"
    status: "True"
    type: Ready
  - lastProbeTime: "2023-06-21T22:08:25Z"
    lastTransitionTime: "2023-06-21T21:09:40Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: "2023-06-21T22:08:25Z"
    lastTransitionTime: "2023-06-21T21:09:19Z"
    status: "True"
    type: PodScheduled
  containerState:
    running:
      startedAt: "2023-06-21T21:09:27Z"
  readyReplicas: 1
