apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    chains.tekton.dev/signed: "true"
  creationTimestamp: "2023-06-21T20:54:43Z"
  finalizers:
  - chains.tekton.dev/pipelinerun
  generateName: ingest-and-train-run-
  generation: 1
  labels:
    tekton.dev/pipeline: ingest-and-train
  name: ingest-and-train-run-btk95
  namespace: pipelines-tutorial
  resourceVersion: "760731"
  uid: 1bf05ee5-9037-4fcb-bff6-1bbb9a20b301
spec:
  params:
  - name: ACCESS_KEY
    value: minioadmin
  - name: BOB
    value: "42"
  - name: IMAGE
    value: image-registry.openshift-image-registry.svc:5000/$(context.pipelineRun.namespace)/ingest-and-train
  - name: S3_ENDPOINT
    value: minio-pipelines-tutorial.apps.cluster-xx7jv.xx7jv.sandbox1365.opentlc.com
  - name: SECRET_KEY
    value: minioadmin
  - name: deployment-name
    value: ingest-and-train
  - name: git-url
    value: https://github.com/redhat-na-ssa/stock.git
  pipelineRef:
    name: ingest-and-train
  taskRunTemplate:
    serviceAccountName: pipeline
  timeouts:
    pipeline: 1h0m0s
  workspaces:
  - name: shared-workspace
    persistentVolumeClaim:
      claimName: my-pipeline-claim-01
status:
  childReferences:
  - apiVersion: tekton.dev/v1beta1
    kind: TaskRun
    name: ingest-and-train-run-btk95-fetch-repository
    pipelineTaskName: fetch-repository
  - apiVersion: tekton.dev/v1beta1
    kind: TaskRun
    name: ingest-and-train-run-btk95-build
    pipelineTaskName: build
  - apiVersion: tekton.dev/v1beta1
    kind: TaskRun
    name: ingest-and-train-run-btk95-ingest-train
    pipelineTaskName: ingest-train
  completionTime: "2023-06-21T21:00:30Z"
  conditions:
  - lastTransitionTime: "2023-06-21T21:00:30Z"
    message: 'Tasks Completed: 3 (Failed: 0, Cancelled 0), Skipped: 0'
    reason: Succeeded
    status: "True"
    type: Succeeded
  pipelineSpec:
    params:
    - description: name of the deployment to be patched
      name: deployment-name
      type: string
    - description: url of the git repo for the code of deployment
      name: git-url
      type: string
    - default: main
      description: revision to be used from repo of the code for deployment
      name: git-revision
      type: string
    - description: image to be build from the code
      name: IMAGE
      type: string
    - description: ENV testing
      name: BOB
      type: string
    - description: minio access_key
      name: ACCESS_KEY
      type: string
    - description: minio secret_key
      name: SECRET_KEY
      type: string
    - description: minio endpoint
      name: S3_ENDPOINT
      type: string
    tasks:
    - name: fetch-repository
      params:
      - name: url
        value: https://github.com/redhat-na-ssa/stock.git
      - name: subdirectory
        value: ""
      - name: deleteExisting
        value: "true"
      - name: revision
        value: main
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
      - name: output
        workspace: shared-workspace
    - name: build
      params:
      - name: IMAGE
        value: image-registry.openshift-image-registry.svc:5000/pipelines-tutorial/ingest-and-train
      runAfter:
      - fetch-repository
      taskRef:
        kind: ClusterTask
        name: s2i-python
      workspaces:
      - name: source
        workspace: shared-workspace
    - name: ingest-train
      params:
      - name: IMAGE
        value: image-registry.openshift-image-registry.svc:5000/pipelines-tutorial/ingest-and-train
      - name: BOB
        value: "42"
      - name: ACCESS_KEY
        value: minioadmin
      - name: SECRET_KEY
        value: minioadmin
      - name: S3_ENDPOINT
        value: minio-pipelines-tutorial.apps.cluster-xx7jv.xx7jv.sandbox1365.opentlc.com
      runAfter:
      - build
      taskRef:
        kind: Task
        name: ingest-train
      workspaces:
      - name: source
        workspace: shared-workspace
    workspaces:
    - name: shared-workspace
  startTime: "2023-06-21T20:54:43Z"
