apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: ingest-train
spec:
  workspaces:
  - name: source
  params:
    - name: manifest_dir
      description: The directory in source that contains yaml manifests
      type: string
      default: "k8s"
    - description: The image
      name: IMAGE
      type: string
    - name: BOB
      type: string
      description: ENV test
      default: "xyz"
    - name: ACCESS_KEY
      type: string
      description: ENV test
    - name: SECRET_KEY
      type: string
      description: ENV test
    - name: S3_ENDPOINT
      type: string
      description: ENV test

  steps:
    - name: ingest
      image: $(params.IMAGE)
      workingDir: /workspace/source
      command: ["python", "src/01-yahoo2csv.py"]
      args:
        - |-
          echo -----------------------------------
      env:
        - name: "BOB"
          value: $(params.BOB)
        - name: "ACCESS_KEY"
          value: $(params.ACCESS_KEY)
        - name: "ACCESS_SECRET"
          value: $(params.ACCESS_SECRET)
        - name: "S3_ENDPOINT"
          value: $(params.S3_ENDPOINT)

    - name: train
      image: $(params.IMAGE)
      workingDir: /workspace/source
      command: ["python", "src/02-train-stock-model-keras.py"]
      args:
        - |-
          echo -----------------------------------
      env:
        - name: "BOB"
          value: $(params.BOB)
        - name: "ACCESS_KEY"
          value: $(params.ACCESS_KEY)
        - name: "ACCESS_SECRET"
          value: $(params.ACCESS_SECRET)
        - name: "S3_ENDPOINT"
          value: $(params.S3_ENDPOINT)
