apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: ingest-train
spec:
  workspaces:
  - name: source
  params:
    - name: manifest_dir
      description: The directory in source that contains yaml manifests
      type: string
      default: "k8s"
    - description: The image
      name: IMAGE
      type: string
  steps:
    - name: ingest
      image: $(params.IMAGE)
      workingDir: /workspace/source
      command: ["python", "src/01-yahoo2csv.py"]
      args:
        - |-
          echo -----------------------------------
    - name: train
      image: $(params.IMAGE)
      workingDir: /workspace/source
      command: ["python", "src/02-train-stock-model-keras.py"]
      args:
        - |-
          echo -----------------------------------
