apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: ingest-train
spec:
  workspaces:
  - name: source
  params:
    - description: Container image used to run the tasks
      name: IMAGE
      type: string
      default: ingest-and-train
    - name: S3_ACCESS_KEY_ID
      type: string
      description: S3 ACCESS KEY
      default: "minioadmin"
    - name: S3_SECRET_ACCESS_KEY
      type: string
      description: S3 SECRET ACCESS KEY
      default: "minioadmin"
    - name: S3_ENDPOINT
      type: string
      description: Used to define the endpoint serving S3 storage
      default: "http://minio:9000"

  steps:
    - name: ingest
      image: image-registry.openshift-image-registry.svc:5000/$(context.taskRun.namespace)/$(params.IMAGE)
      workingDir: /workspace/source/src/src
      command:
        - "python"
        - "01-get-data.py"
      args:
        - |-
          echo -----------------------------------
      env:
        - name: "AWS_ACCESS_KEY_ID"
          value: $(params.S3_ACCESS_KEY_ID)
        - name: "AWS_SECRET_ACCESS_KEY"
          value: $(params.S3_SECRET_ACCESS_KEY)
        - name: "AWS_S3_ENDPOINT"
          value: $(params.S3_ENDPOINT)
    - name: train
      image: image-registry.openshift-image-registry.svc:5000/$(context.taskRun.namespace)/$(params.IMAGE)
      workingDir: /workspace/source/src/src
      command: 
        - "python"
        - "02-train-model.py"
      args:
        - |-
          echo -----------------------------------
      env:
        - name: "S3_ACCESS_KEY_ID"
          value: $(params.S3_ACCESS_KEY_ID)
        - name: "S3_SECRET_ACCESS_KEY"
          value: $(params.S3_SECRET_ACCESS_KEY)
        - name: "S3_ENDPOINT"
          value: $(params.S3_ENDPOINT)
